nvchecker:
  regex: Anaconda3-([\d.-]+)-Linux-x86_64.sh
  source: regex
  url: https://repo.anaconda.com/archive/
  from_pattern: '-'
  to_pattern: .
test: true
oldver: 2025.06.1
clean-up-ubuntu: true
