[__config__]
oldver = "cache/oldver.json"
newver = "cache/newver.json"
#keyfile = "keyfile.toml"

[apache-lucene]
source = "regex"
regex = 'lucene-([\d.]+)-src.tgz'
url = "https://lucene.apache.org/core/downloads.html"

[github-actions-bin]
source = "github"
github = "actions/runner"
use_latest_release = true

[heasoft]
source = "regex"
regex = 'RELEASE NOTES FOR HEASOFT ([\d.]+)'
url = "https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/release_notes.html"

[hypre]
source = "github"
github = "hypre-space/hypre"
use_max_tag = true

[jgit]
source = "regex"
regex = 'Direct Download ([\d.]+.*)</h2>'
url = "http://www.eclipse.org/jgit/download/"

[kahip]
source = "github"
github = "KaHIP/KaHIP"
use_latest_release = true

[openfoam]
source = "github"
github = "OpenFOAM/OpenFOAM-10"
use_latest_tag = true

[petsc-complex]
source = "regex"
regex = 'petsc-([\d.]+).tar.gz'
url = "https://petsc.org/release/download/"

[python-audioread]
source = "github"
github = "beetbox/audioread"
use_latest_tag = true

[python-cupy]
source = "github"
github = "cupy/cupy"
use_latest_release = true

[python-imread]
source = "github"
github = "luispedro/imread"
use_max_tag = true

[python-librosa]
source = "github"
github = "librosa/librosa"
use_latest_release = true

[python-multiprocess]
source = "github"
github = "uqfoundation/multiprocess"
use_latest_release = true

[python-numpy-mkl]
source = "github"
github = "numpy/numpy"
use_latest_release = true

[python-mkl-random]
source = "github"
github = "IntelPython/mkl_random"
use_latest_release = true

[python-resampy]
source = "github"
github = "bmcfee/resampy"
use_latest_release = true

[python-scipy-mkl]
source = "github"
github = "scipy/scipy"
use_latest_release = true

[python-url-normalize]
source = "github"
github = "niksite/url-normalize"
use_latest_release = true

[spek]
source = "github"
github = "alexkay/spek"
use_latest_release = true
