[__config__]
oldver = "cache/oldver.json"
newver = "cache/newver.json"
#keyfile = "keyfile.toml"

[anaconda]
source = "regex"
regex = 'Anaconda3-([\d.]+)-Linux-x86_64.sh'
url = "https://repo.anaconda.com/archive/"

[apache-lucene]
source = "regex"
regex = 'lucene-([\d.]+)-src.tgz'
url = "https://lucene.apache.org/core/downloads.html"

[basix]
source = "github"
github = "FEniCS/basix"
use_latest_release = true

[cp2k-bin]
source = "github"
github = "cp2k/cp2k"
use_latest_release = true

[dolfinx]
source = "github"
github = "FEniCS/dolfinx"
use_latest_release = true

[fet-timetabling]
source = "regex"
regex = 'fet-([\d.]+).tar.bz2'
url = "https://lalescu.ro/liviu/fet/download.html"

[github-actions-bin]
source = "github"
github = "actions/runner"
use_latest_release = true

[heasoft]
source = "regex"
regex = 'RELEASE NOTES FOR HEASOFT ([\d.]+)'
url = "https://heasarc.gsfc.nasa.gov/docs/software/lheasoft/release_notes.html"

[hypre]
source = "github"
github = "hypre-space/hypre"
use_max_tag = true

[jgit]
source = "regex"
regex = 'Direct Download ([\d.]+.*)</h2>'
url = "http://www.eclipse.org/jgit/download/"

[kahip]
source = "github"
github = "KaHIP/KaHIP"
use_latest_release = true

[libxc]
source = "gitlab"
gitlab = "libxc/libxc"
use_max_tag = true

[mumps-par]
source = "regex"
regex = '<a href="index.php\?page=dwnld">([\d.]+.*)</a>'
url = "https://graal.ens-lyon.fr/MUMPS/index.php"

[netron]
source = "github"
github = "lutzroeder/netron"
use_latest_release = true

[nni]
source = "github"
github = "microsoft/nni"
use_latest_release = true

[openfoam]
source = "github"
github = "OpenFOAM/OpenFOAM-10"
use_latest_tag = true

[petsc-complex]
source = "regex"
regex = 'petsc-([\d.]+).tar.gz'
url = "https://petsc.org/release/download/"

[python-audioread]
source = "github"
github = "beetbox/audioread"
use_latest_tag = true

[python-cupy]
source = "github"
github = "cupy/cupy"
use_latest_release = true

[python-fenics-basix]
source = "github"
github = "FEniCS/basix"
use_latest_release = true

[python-fenics-dolfinx]
source = "github"
github = "FEniCS/dolfinx"
use_latest_release = true

[python-fenics-ffcx]
source = "github"
github = "FEniCS/ffcx"
use_latest_release = true

[python-fenics-ufl]
source = "github"
github = "FEniCS/ufl"
use_latest_release = true

[python-imread]
source = "github"
github = "luispedro/imread"
use_max_tag = true

[python-librosa]
source = "github"
github = "librosa/librosa"
use_latest_release = true

[python-mkl-random]
source = "github"
github = "IntelPython/mkl_random"
use_latest_release = true

[python-mkl-service]
source = "github"
github = "IntelPython/mkl-service"
use_latest_release = true

[python-multiprocess]
source = "github"
github = "uqfoundation/multiprocess"
use_latest_release = true

[python-numpy-mkl]
source = "github"
github = "numpy/numpy"
use_latest_release = true

[python-pydotplus]
source = "pypi"
pypi = "pydotplus"

[python-pydub]
source = "github"
github = "jiaaro/pydub"
use_latest_release = true

[python-pywavelets]
source = "github"
github = "pywavelets/pywt"
use_latest_release = true

[python-requests-cache]
source = "github"
github = "requests-cache/requests-cache"
use_max_tag = true

[python-resampy]
source = "github"
github = "bmcfee/resampy"
use_latest_release = true

[python-scipy-mkl]
source = "github"
github = "scipy/scipy"
use_latest_release = true

[python-url-normalize]
source = "github"
github = "niksite/url-normalize"
use_latest_release = true

[r-bas]
source = "regex"
regex = 'BAS_([\d.]+).tar.gz'
url = "https://cran.r-project.org/web/packages/BAS/index.html"

[spek]
source = "github"
github = "alexkay/spek"
use_latest_release = true

[superlu_dist]
source = "github"
github = "xiaoyeli/superlu_dist"
use_latest_release = true

[tfsec-bin]
source = "github"
github = "aquasecurity/tfsec"
use_latest_tag = true
