name: Build test

run-name: Build test for ${{ inputs.pkgbase }} ${{ inputs.pkgver }}

on:
  workflow_dispatch:
    inputs:
      pkgbase:
        required: true
      pkgver:
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    outputs:
      built: ${{ steps.build.outputs.built }}

    steps:
      - uses: arch4edu/cactus/actions/upgrade-archlinux@main

      - name: Install runtime dependencies
        run: pacman -S --noconfirm --needed base-devel devtools dbus git pacman-contrib

      - uses: arch4edu/cactus/actions/config-makepkg@main

      - uses: actions/checkout@master

      - name: Add path
        run: echo "$(realpath bin)" >> $GITHUB_PATH

      - name: Override update script
        run: |
          find config -name ${{ github.event.inputs.pkgbase }}.override -exec cp {} bin/update-pkgver \;
          chmod +x bin/update-pkgver

      - name: Configure custom repository
        run: |
          [ -z "$(find config -name ${{ github.event.inputs.pkgbase }}.repository)" ] && exit 0
          cat /usr/share/devtools/pacman.conf.d/extra.conf $(find config -name ${{ github.event.inputs.pkgbase }}.repository) > /usr/share/devtools/pacman.conf.d/custom.conf
          ln -s /usr/bin/archbuild /usr/bin/custom-x86_64-build

      - name: Build ${{ github.event.inputs.pkgbase }} ${{ inputs.pkgver }}
        id: build
        run: |
          aur-clone ${{ github.event.inputs.pkgbase }}
          cd ${{ github.event.inputs.pkgbase }}
          update-pkgver ${{ github.event.inputs.pkgver }}
          if [ -f /usr/bin/custom-x86_64-build ]
          then
            su makepkg -c custom-x86_64-build || :
          else
            su makepkg -c extra-x86_64-build || :
          fi
          [ -n "$(find -maxdepth 1 -name '*.pkg.tar.zst')" ] && echo "built=1" >> "$GITHUB_OUTPUT" || echo "built=0" >> "$GITHUB_OUTPUT"

  push:
    needs: build
    if: ${{ needs.build.outputs.built == 1 }}
    concurrency: nvchecker
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
      - uses: arch4edu/cactus/actions/upgrade-archlinux@main
        id: init

      - name: Install runtime dependencies
        run: pacman -S --noconfirm --needed base-devel git nvchecker openssh pacman-contrib python-toml python-yaml

      - uses: actions/checkout@master

      - name: Set up nvchecker cache
        uses: actions/cache@master
        with:
          path: cache
          key: nvchecker-${{ steps.init.outputs.time }}
          restore-keys: nvchecker-

      - name: Add path
        run: echo "$(realpath bin)" >> $GITHUB_PATH

      - name: Configure git makepkg and ssh
        run: |
          echo "${{ secrets.SSH_KEY }}" | install -Dm400 /dev/stdin /root/.ssh/aur
          cp ssh_config /root/.ssh/config
          git config --global user.name 'Auto update bot'
          git config --global user.email 'auto-update-bot@arch4edu.org'
          useradd makepkg

      - name: Override update script
        run: |
          find config -name ${{ github.event.inputs.pkgbase }}.override -exec cp {} bin/update-pkgver \;
          chmod +x bin/update-pkgver

      - name: Push ${{ github.event.inputs.pkgbase }} ${{ inputs.pkgver }} to AUR
        run: |
          aur-clone ${{ github.event.inputs.pkgbase }}
          cd ${{ github.event.inputs.pkgbase }}
          update-pkgver ${{ github.event.inputs.pkgver }}
          aur-push

      - name: Update the nvchecker cache
        run: |
          python nvchecker.py $(find config -name ${{ github.event.inputs.pkgbase }}.yaml)
          nvtake -c nvchecker.toml ${{ github.event.inputs.pkgbase }}
